import { Mail, MessageCircle, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useI18n, type Language } from "@/contexts/I18nContext";
import { StoreFooter } from "@/components/StorePrimitives";

const store = { owner: "Issa Cisse", email: "Issacisse.x@gmail.com", whatsapp: "33362993", location: "Nouakchott, Mauritania" };

type LegalKind = "privacy" | "terms" | "refund" | "contact";
const text: Record<Language, Record<LegalKind | "title" | "updated" | "back" | "owner" | "email" | "whatsapp" | "location" | "support", string>> = {
  ar: { privacy: "سياسة الخصوصية", terms: "شروط الاستخدام", refund: "سياسة الاسترجاع", contact: "اتصل بنا", title: "معلومات المتجر", updated: "آخر تحديث: 30 أغسطس 2026", back: "العودة إلى المتجر", owner: "صاحب المتجر", email: "البريد الإلكتروني", whatsapp: "واتساب", location: "الموقع", support: "الدعم" },
  fr: { privacy: "Politique de confidentialité", terms: "Conditions d’utilisation", refund: "Politique de remboursement", contact: "Contactez-nous", title: "Informations de la boutique", updated: "Dernière mise à jour : 30 août 2026", back: "Retour à la boutique", owner: "Propriétaire", email: "E-mail", whatsapp: "WhatsApp", location: "Localisation", support: "Assistance" },
  en: { privacy: "Privacy policy", terms: "Terms of use", refund: "Refund policy", contact: "Contact us", title: "Store information", updated: "Last updated: August 30, 2026", back: "Back to store", owner: "Store owner", email: "Email", whatsapp: "WhatsApp", location: "Location", support: "Support" },
};

const copy: Record<Language, Record<LegalKind, { intro: string; sections: Array<[string, string]> }>> = {
  ar: {
    privacy: { intro: "نحترم خصوصيتك. تجمع لُعْبَة الحد الأدنى من البيانات اللازمة لمعالجة الطلبات وتقديم الملفات الرقمية والدعم.", sections: [["البيانات التي نستخدمها", "قد نطلب اسمك وبريدك الإلكتروني وتفاصيل الطلب. لا نطلب بيانات بطاقة مصرفية؛ تتم معالجة الدفع عبر Cryptomus وفق إعدادات حساب التاجر."], ["الملفات والاحتفاظ", "نحتفظ بسجل الطلب بالقدر اللازم لتأكيد الدفع وتوفير رابط التنزيل والرد على طلبات الدعم. يمكنك طلب تصحيح بياناتك أو حذفها عبر البريد الإلكتروني."], ["المشاركة والأمان", "لا نبيع بيانات العملاء. قد نشارك الحد الأدنى الضروري مع مزودي الدفع أو التخزين لتقديم الخدمة، ونحمي مفاتيح API في الخادم ولا نضعها في كود المتصفح."], ["التواصل", "لأي سؤال متعلق بالخصوصية، تواصل مع Issa Cisse عبر البريد المذكور في صفحة الاتصال."]] },
    terms: { intro: "باستخدامك هذا المتجر، توافق على الشروط التالية الخاصة بشراء المنتجات الرقمية.", sections: [["المنتجات الرقمية", "تُباع المنتجات كملفات رقمية، ولا يوجد شحن مادي. بعد تأكيد الدفع، يُتاح رابط التنزيل للعميل عبر صفحة الطلب."], ["الأسعار والدفع", "تظهر الأسعار بالدولار الأمريكي. الدفع متاح عبر Cryptomus باستخدام USDT والشبكة التي يختارها العميل. لا يُعتبر الطلب مدفوعًا حتى يؤكده النظام من خلال إشعار الدفع."], ["الاستخدام المسموح", "الشراء للاستخدام الشخصي أو للاستخدام المرخص الموضح في صفحة المنتج. لا يجوز إعادة بيع الملفات أو إعادة توزيعها أو ادعاء ملكيتها."], ["التعديلات والتواصل", "قد نحدّث المنتجات أو هذه الشروط عند الحاجة. للاستفسارات، استخدم بيانات الاتصال المنشورة في هذه الصفحة."]] },
    refund: { intro: "نبيع ملفات رقمية؛ لذلك نطبق سياسة استرجاع واضحة مرتبطة بحالة التنزيل وجودة الملف.", sections: [["متى يمكن طلب الاسترجاع؟", "يمكن طلب الاسترجاع قبل تنزيل الملف إذا تعذر توفير المنتج أو لم يتم تأكيد الطلب بشكل صحيح. إذا كان الملف معيبًا، سنحاول أولًا توفير نسخة سليمة أو إصلاح المشكلة."], ["بعد التنزيل", "بعد بدء تنزيل الملف لا يُقبل الاسترجاع عادةً، إلا إذا ثبت وجود عيب تقني غير قابل للإصلاح أو كان الملف مختلفًا بشكل جوهري عن وصفه."], ["طريقة الطلب", "أرسل رقم الطلب ووصف المشكلة من البريد الإلكتروني المستخدم في الشراء إلى Issacisse.x@gmail.com. سنراجع الطلب ونرد خلال مدة معقولة."], ["الاسترداد", "إذا تمت الموافقة، يُعاد المبلغ عبر الطريقة التي يحددها مزود الدفع أو وفق ما يمكن تنفيذه بأمان بعد التحقق من الطلب."]] },
    contact: { intro: "يسعدنا مساعدتك في أسئلة المنتجات والطلبات والتنزيلات.", sections: [["بيانات المتجر", "صاحب المتجر: Issa Cisse\nالموقع: نواكشوط، موريتانيا"], ["الدعم عبر البريد", "Issacisse.x@gmail.com"], ["واتساب", "33362993"], ["قبل التواصل", "أرسل رقم الطلب والبريد المستخدم في الشراء، ولا ترسل مفاتيح API أو كلمات المرور أو بيانات محافظك الخاصة."]] },
  },
  fr: {
    privacy: { intro: "Nous respectons votre vie privée. لُعْبَة utilise uniquement les données nécessaires pour traiter les commandes, livrer les fichiers numériques et assurer l’assistance.", sections: [["Données utilisées", "Nous pouvons demander votre nom, votre adresse e-mail et les détails de votre commande. Nous ne demandons pas de données de carte bancaire ; le paiement est traité par Cryptomus."], ["Conservation", "Nous conservons les informations nécessaires pour confirmer le paiement, fournir le téléchargement et répondre au support. Vous pouvez demander une correction ou une suppression par e-mail."], ["Partage et sécurité", "Nous ne vendons pas les données clients. Les clés API restent côté serveur et ne sont jamais placées dans le code client."], ["Contact", "Pour toute question de confidentialité, contactez Issa Cisse à l’adresse indiquée sur la page Contact."]] },
    terms: { intro: "En utilisant cette boutique, vous acceptez les conditions applicables aux achats numériques.", sections: [["Produits numériques", "Les produits sont livrés sous forme de fichiers numériques ; aucun envoi physique n’est prévu. Le téléchargement devient disponible après confirmation du paiement."], ["Prix et paiement", "Les prix sont affichés en dollars américains. Le paiement est proposé via Cryptomus en USDT, avec le réseau choisi par le client. Une commande n’est considérée comme payée qu’après confirmation système."], ["Usage autorisé", "Les fichiers sont destinés à l’usage personnel ou à la licence indiquée sur la fiche produit. Toute revente ou redistribution est interdite."], ["Mises à jour", "Nous pouvons mettre à jour les produits ou ces conditions. Contactez-nous via les coordonnées publiées pour toute question."]] },
    refund: { intro: "Les produits étant numériques, notre politique de remboursement dépend de l’état du téléchargement et de la qualité du fichier.", sections: [["Avant le téléchargement", "Un remboursement peut être demandé avant le téléchargement si le produit ne peut pas être fourni ou si la commande n’est pas correctement confirmée. Pour un fichier défectueux, nous proposerons d’abord une correction ou une nouvelle version."], ["Après le téléchargement", "Après le début du téléchargement, le remboursement n’est généralement pas accepté, sauf défaut technique non réparable ou différence substantielle avec la description."], ["Demande", "Envoyez le numéro de commande et la description du problème depuis l’adresse utilisée lors de l’achat à Issacisse.x@gmail.com."], ["Traitement", "En cas d’acceptation, le remboursement sera effectué via la méthode permise par le prestataire de paiement après vérification de la commande."]] },
    contact: { intro: "Nous sommes disponibles pour les questions sur les produits, commandes et téléchargements.", sections: [["Boutique", "Propriétaire : Issa Cisse\nLocalisation : Nouakchott, Mauritanie"], ["E-mail", "Issacisse.x@gmail.com"], ["WhatsApp", "33362993"], ["Pour nous aider", "Indiquez votre numéro de commande et l’e-mail utilisé. N’envoyez jamais de clés API, mots de passe ou clés privées."]] },
  },
  en: {
    privacy: { intro: "We respect your privacy. لُعْبَة uses only the information needed to process orders, deliver digital files, and provide support.", sections: [["Information we use", "We may ask for your name, email address, and order details. We do not request card details; payments are handled through Cryptomus."], ["Retention", "We retain information needed to confirm payment, provide downloads, and answer support requests. You may ask us to correct or delete your information by email."], ["Sharing and security", "We do not sell customer data. API keys remain server-side and are never placed in client code."], ["Contact", "For privacy questions, contact Issa Cisse using the email shown on the Contact page."]] },
    terms: { intro: "By using this store, you agree to these terms for digital purchases.", sections: [["Digital products", "Products are delivered as digital files; there is no physical shipping. A download becomes available after payment confirmation."], ["Prices and payment", "Prices are shown in US dollars. Payment is provided through Cryptomus in USDT using the network selected by the customer. An order is paid only after system confirmation."], ["Permitted use", "Files are for personal use or the licence stated on the product page. Resale and redistribution are not allowed."], ["Updates", "We may update products or these terms when necessary. Contact us using the published support details."]] },
    refund: { intro: "Because products are digital, refunds depend on the download status and file quality.", sections: [["Before download", "A refund may be requested before download if the product cannot be delivered or the order was not confirmed correctly. For a defective file, we will first try to provide a corrected version."], ["After download", "After downloading begins, refunds are generally unavailable unless there is an unrepairable technical defect or a material difference from the description."], ["How to request", "Send the order number and a description of the issue from the purchasing email to Issacisse.x@gmail.com."], ["Processing", "If approved, the refund will be handled through the payment method permitted by the payment provider after order verification."]] },
    contact: { intro: "We are happy to help with product, order, and download questions.", sections: [["Store", "Owner: Issa Cisse\nLocation: Nouakchott, Mauritania"], ["Email support", "Issacisse.x@gmail.com"], ["WhatsApp", "33362993"], ["Before contacting us", "Include your order number and purchasing email. Never send API keys, passwords, or private wallet keys."]] },
  },
};

export default function Legal({ kind }: { kind: LegalKind }) {
  const { lang } = useI18n();
  const labels = text[lang];
  const page = copy[lang][kind];
  return <div className="store-shell legal-shell"><main className="inner-page"><div className="container legal-top"><Link href="/" className="checkout-brand"><span className="brand-mark"><span>ل</span></span><strong>لُعْبَة</strong></Link><Link href="/" className="back-cart">{labels.back}</Link></div><article className="container legal-page"><div className="legal-heading"><span className="eyebrow">{labels.title}</span><h1>{labels[kind]}</h1><p>{labels.updated}</p></div><div className="legal-intro"><ShieldCheck size={20} /> <span>{page.intro}</span></div>{page.sections.map(([heading, body]) => <section className="legal-section" key={heading}><h2>{heading}</h2><p>{body}</p></section>)}{kind === "contact" && <div className="contact-cards"><a href={`mailto:${store.email}`}><Mail size={18} /><span>{labels.email}<b>{store.email}</b></span></a><a href={`https://wa.me/222${store.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18} /><span>{labels.whatsapp}<b>{store.whatsapp}</b></span></a></div>}</article></main><StoreFooter /></div>;
}

export function LegalRoute() {
  const [, params] = useRoute("/legal/:kind");
  const kind = ["privacy", "terms", "refund", "contact"].includes(params?.kind || "") ? params?.kind as LegalKind : "privacy";
  return <Legal kind={kind} />;
}
