import { ArrowRight, CheckCircle2, ExternalLink, KeyRound, Settings2, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useI18n, type Language } from "@/contexts/I18nContext";

const copy: Record<Language, { title: string; intro: string; back: string; ready: string; server: string; adsense: string; adsenseBody: string; crypto: string; cryptoBody: string; paypal: string; paypalBody: string; env: string; security: string; contact: string }> = {
  ar: { title: "إعدادات المتجر", intro: "مركز واحد لتجهيز الإعلانات والدفع دون تعديل كود المتجر.", back: "العودة إلى المتجر", ready: "جاهز للإعداد", server: "يُضبط من أسرار المشروع", adsense: "Google AdSense", adsenseBody: "أضف Publisher ID بصيغة ca-pub-… بعد قبول موقعك في AdSense. مواضع الإعلانات موجودة في الصفحة الرئيسية.", crypto: "Cryptomus · USDT", cryptoBody: "أضف Merchant ID وPayment API Key بعد اعتماد التاجر. يدعم المتجر TRC20 وBEP20 وERC20 وSolana وArbitrum.", paypal: "PayPal", paypalBody: "الواجهة محفوظة للإضافة لاحقًا. يلزم Client ID وClient Secret في أسرار الخادم، ولا تظهر هذه القيم للزوار.", env: "ملاحظة أمنية", security: "لا تضع أي مفتاح سري هنا أو في كود المتصفح. استخدم إعدادات Secrets في لوحة المشروع فقط.", contact: "تحتاج مساعدة؟ Issacisse.x@gmail.com" },
  fr: { title: "Réglages de la boutique", intro: "Un espace unique pour préparer la publicité et les paiements sans modifier le code.", back: "Retour à la boutique", ready: "Prêt à configurer", server: "Configuré dans les secrets du projet", adsense: "Google AdSense", adsenseBody: "Ajoutez votre Publisher ID au format ca-pub-… après l’acceptation du site. Les emplacements sont déjà présents sur l’accueil.", crypto: "Cryptomus · USDT", cryptoBody: "Ajoutez le Merchant ID et la Payment API Key après validation du marchand. Les réseaux TRC20, BEP20, ERC20, Solana et Arbitrum sont prêts.", paypal: "PayPal", paypalBody: "L’espace est prévu pour une activation ultérieure. Le Client ID et le Client Secret restent côté serveur.", env: "Note de sécurité", security: "Ne placez jamais une clé secrète ici ou dans le code du navigateur. Utilisez les Secrets du projet.", contact: "Besoin d’aide ? Issacisse.x@gmail.com" },
  en: { title: "Store settings", intro: "One place to prepare advertising and payments without editing the store code.", back: "Back to store", ready: "Ready to configure", server: "Configured in project secrets", adsense: "Google AdSense", adsenseBody: "Add your ca-pub-… Publisher ID after your site is accepted by AdSense. Ad placements are already present on the homepage.", crypto: "Cryptomus · USDT", cryptoBody: "Add the Merchant ID and Payment API Key after merchant approval. TRC20, BEP20, ERC20, Solana, and Arbitrum are ready.", paypal: "PayPal", paypalBody: "This space is reserved for a later activation. Client ID and Client Secret remain server-side.", env: "Security note", security: "Never place a secret key here or in browser code. Use the project Secrets settings.", contact: "Need help? Issacisse.x@gmail.com" },
};

export default function Settings() {
  const { lang } = useI18n();
  const t = copy[lang];
  const cards = [{ name: t.adsense, body: t.adsenseBody, icon: "A", href: "https://www.google.com/adsense/" }, { name: t.crypto, body: t.cryptoBody, icon: "₿", href: "https://business.cryptomus.com/" }, { name: t.paypal, body: t.paypalBody, icon: "P", href: "https://developer.paypal.com/dashboard/" }];
  return <div className="store-shell settings-shell"><main className="inner-page"><div className="container settings-top"><Link href="/" className="checkout-brand"><span className="brand-mark"><span>ل</span></span><strong>لُعْبَة</strong></Link><Link href="/" className="back-cart"><ArrowRight size={15} /> {t.back}</Link></div><section className="container settings-page"><div className="settings-hero"><span className="settings-icon"><Settings2 size={25} /></span><div><span className="eyebrow">Little Leaf Market</span><h1>{t.title}</h1><p>{t.intro}</p></div></div><div className="settings-grid">{cards.map(card => <article className="settings-card" key={card.name}><div className="settings-card-head"><span className="integration-mark">{card.icon}</span><div><h2>{card.name}</h2><span className="settings-status"><CheckCircle2 size={14} /> {t.ready}</span></div></div><p>{card.body}</p><div className="settings-card-foot"><span><KeyRound size={14} /> {t.server}</span><a href={card.href} target="_blank" rel="noreferrer" aria-label={card.name}><ExternalLink size={15} /></a></div></article>)}</div><div className="settings-security"><ShieldCheck size={20} /><div><strong>{t.env}</strong><p>{t.security}</p></div></div><p className="settings-contact">{t.contact}</p></section></main></div>;
}
